version: '2'
services:
    edu-app:
        image: edu
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://edu-postgresql:5432/edu
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    edu-postgresql:
        extends:
            file: postgresql.yml
            service: edu-postgresql
