version: '2'
services:
    edu-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/edu/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=edu
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
